### ISSUE TITLE
site redirects to logout page.

### ISSUE THREAD

**Issue by anaamnizami** [yilmaznaslan/termin101#4]
Hey have you experienced this issue, when ever bot loads the page, site redirects to the logout page.

**Comment by yilmaznaslan** [comment]
Yes I have recently discovered that. Before making any call the sessionId must be activated. I will implement the fix soon

**Comment by cynthias13w** [comment]
I also have the same issue. Any follow-up? :)

**Comment by iamjosephmj** [comment]
Hey, are there any updates on this?

**Comment by yilmaznaslan** [comment]
Probably you don't need anymore but here it is https://github.com/yilmaznaslan/berlinTerminFinder
